SELECT 
TABLE_NAME AS Tabla,
COLUMN_NAME AS Campo,
COLUMN_TYPE AS Tipo_de_dato,
IS_NULLABLE AS Permite_Null,
COLUMN_KEY AS Llave,
COLUMN_DEFAULT AS Valor_Por_Defecto,
EXTRA AS Extra
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'sena_access'
ORDER BY TABLE_NAME;